### ISSUE TITLE
Use SpannerConnectionMetadata in the connection

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#199]
Connection should not return null. It should instead return `SpannerConnectionMetadata`, a trivial implementation that does not change with connection, implemented in #163.

The task is:
1) Define a singleton INSTANCE in `SpannerConnectionMetadata`, similar to the one in [H2 implementation](https://github.com/r2dbc/r2dbc-h2/commit/d6a0bdbd7ddd9ae437c5538c8ebddfe472aaeec2).
2) Return the static instance from `SpannerConnection.getMetadata()`:
https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/blob/572212ca74d827cdace1a6af91e0ccce42d80fba/cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java#L264
3) Write tests for both changes.

**Comment by itssanjib** [comment]
@elefeint Thank you very much for welcoming in open source. I really love to work on this issue. Please assign me this issue.

**Comment by itssanjib** [comment]
@elefeint Let me know how to start with it? Firstly I have to fork a branch for me and set up locally? If any discussion is required or facing any challenge how to communicate?

**Comment by elefeint** [comment]
Yes -- fork the repo, set up a new branch and do the work in it. 
Make sure unit tests pass (you will not be able to run integration tests without a GCP project; one of us can run integration tests on your PR once you are done). To run unit tests only:
```
mvn clean install -DskipITs
``` 

Once you are happy with the code, create a pull request from your fork/branch to our master.

And take a look at the [README](https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/blob/426d922949e04d9256045ddc4616deb22765740a/CONTRIBUTING.adoc#L45) -- it has information on contributor license agreement and style.

**Comment by itssanjib** [comment]
@elefeint I am facing issue while building this project with maven. Please let me know how can I make the build successful. I am using my service account for building this project with project owner role. Whatever error I am facing sharing as follows.

[ERROR] com.google.cloud.spanner.r2dbc.it.SpannerDdlIT.testCreateAndDrop  Time elapsed: 1.295 s  <<< ERROR!
io.r2dbc.spi.R2dbcNonTransientResourceException: NOT_FOUND: Instance not found: projects/clef-team-project/instances/reactivetest
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Instance not found: projects/clef-team-project/instances/reactivetest

[ERROR] com.google.cloud.spanner.r2dbc.it.SpannerDdlIT.testDdlErrorPropagation  Time elapsed: 1.01 s  <<< ERROR!
io.r2dbc.spi.R2dbcNonTransientResourceException: NOT_FOUND: Instance not found: projects/clef-team-project/instances/reactivetest
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Instance not found: projects/clef-team-project/instances/reactivetest

Please suggest me how to resolve this issue.

**Comment by elefeint** [comment]
Are you using the `-DskipITs` property?

**Comment by itssanjib** [comment]
No I was just using `mvn cean install` . Now I am using `-DskipITs` property and the build get succeeded.

**Comment by itssanjib** [comment]
@elefeint As you have suggest to define a singleton INSTANCE in `SpannerConnectionMetadata`, similar to the one in [H2 implementation](https://github.com/r2dbc/r2dbc-h2/commit/d6a0bdbd7ddd9ae437c5538c8ebddfe472aaeec2). Should I modify the `SpannerConnectionMetadata` `class` to an `enum` like the reference, or I should only add an singleton INSTANCE in it?

**Comment by elefeint** [comment]
Just add the `INSTANCE`; there won't ever be other values there.

**Comment by itssanjib** [comment]
I have modified this way please check once. I will update the test cases if this is correct. Please confirm.

```
public enum SpannerConnectionMetadata implements ConnectionMetadata {

  INSTANCE;

  @Override
  public String getDatabaseProductName() {
    return SpannerConnectionFactoryMetadata.NAME;
  }

  @Override
  public String getDatabaseVersion() {
    return "n/a";
  }
}
```

**Comment by elefeint** [comment]
Yes, this is fine -- you'll need to update `SpannerConnectionMetadataTest` since this becomes an enum.

**Comment by itssanjib** [comment]
@elefeint I have done my side. I have made changes on these files listed below. Should I raise a PR?

```
SpannerConnection.java
SpannerConnectionMetadata.java

SpannerConnectionMetadataTest.java
SpannerConnectionTest.java
```

**Comment by elefeint** [comment]
Yes, please!

**Comment by itssanjib** [comment]
OK. Is there any pattern need to follow for commit message, or I can use my own message style?

**Comment by itssanjib** [comment]
[PR](https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/pull/226) raised. Please validate.

**Comment by itssanjib** [comment]
Facing issue like  `Need a CLA for one or more commit authors`. I have created one, but not resolved. Please suggest what to do?

**Comment by itssanjib** [comment]
@elefeint Thank you! You can refer me more assignments.
