### ISSUE TITLE
Consider how to clean up application-wide Spanner state

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#284]
`Spanner` client library object opens and caches server-side Cloud Spanner sessions. It needs to be [closed properly](https://github.com/googleapis/java-spanner/blob/462839b625e58e235581b8ba10b398e1d222eaaf/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Spanner.java#L108) to avoid exhausting server-side sessions.

As `Spanner` object is meant to be a singleton over the lifetime of the application, we instantiate it once in `SpannerClientLibraryConnectionFactory`. While R2DBC connection objects themselves have a `close()` method for cleaning up resources, the connection factory does not. 

In the Cloud Spanner driver, we have an option of doing something custom, but it may be better to have R2DBC SPI `ConnectionFactories` and `ConnectionFactory` to provide a `close()` interface method:
* something like Spring Data could call ``ConnectionFactories.close()` automatically when closing context
* user applications could call `close()` on an individual connection factory they acquired.

**Comment by elefeint** [comment]
@mp911de Has a question of cleaning up connection factories come up at any point? Cloud Spanner V2 connection factory keeps state that ought to be cleaned up server-side on application shutdown. We can handle it locally in the driver, but cleanup facilities for every level of abstraction seems like a potentially useful SPI feature to have.

**Comment by mp911de** [comment]
There's `io.r2dbc.spi.Closeable` that can be implemented by a `ConnectionFactory`, also `Connection extends Closeable`.

**Comment by elefeint** [comment]
That will work, and we can document that `SpannerConnectionFactory` needs to be closed by the user. But since it's not part of the spec, the connection factory `close()` method won't be called by a client library (such as Spring Data), right?

**Comment by mp911de** [comment]
Spring Data generally doesn't close connection factories, it's the responsibility of application frameworks that provide the entire infrastructure (e.g. Spring Framework/Boot). Would it make sense to extend this responsibility to `ConnectionFactory` delegates such as R2DBC Pool and R2DBC proxy? /cc @ttddyy

**Comment by ttddyy** [comment]
I think responsibility needs to be in application framework(e.g. Spring Boot) since it is managing the application lifecycle. r2dbc-pool/proxy don't know when to really close the `ConnectionFactory`.

For example, in r2dbc-pool, `ConnectionPool` (`ConnectionFactory` implementation) [implements `Closeable`](https://github.com/r2dbc/r2dbc-pool/blob/b16b8aad71bbe78c55943e66278df4758d8cb538/src/main/java/io/r2dbc/pool/ConnectionPool.java#L59).(actually it is implementing `java.io.Closeable` which probably should be `io.r2dbc.spi.Closeable`)
Then, for Spring Boot application, when autoconfiguration creates `ConnectionPool` bean, [it registers destroy method](https://github.com/spring-projects/spring-boot/blob/2d5a55fb0d13796b201de2b68c76ab14b54f03a4/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/r2dbc/ConnectionFactoryConfigurations.java#L65).

I'm ok with `ConnectionFactory` implements `Closeable`. If it happens, Spring Boot needs some generic ways to call `close` method to all `ConnectionFactory` beans. (e.g. `DisposableBean`).

Also, r2dbc-pool/proxy need to call `close` on delegating actual `ConnectionFactory` instance.
I think this provides pretty good guarantee on resource clean up at shutdown time.
Though, it is still application or application layer's framework responsibility to call the `close` at shutdown.

**Comment by meltsufin** [comment]
Cleanup logic will be implemented in `ConnectionFactory.close()`.
