### ISSUE TITLE
Set up Cloud Spanner R2DBC release schedule

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#86]
Discuss releasing on the same schedule as client libraries.

**Comment by meltsufin** [comment]
Just to update on the current state, we're now publishing to Sonatype Maven Central Snapshots repository after each commit to `master`.
Regarding synchronized releases with client libraries, I don't think it makes sense any longer because we're only using the gRPC stubs for Spanner which rarely change.
